### ISSUE TITLE
ArgumentOutOfRangeException after keymashing

### ISSUE THREAD

**Issue by winggar** [winggar/WingCalculator#59]
![image](https://user-images.githubusercontent.com/10767513/153520382-4f893ddc-f95c-4378-ad92-1b659df61d81.png)

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Index was out of range. Must be non-negative and less than the size of the collection.')

**Comment by winggar** [comment]
new stack trace:
```
System.Collections.Generic.KeyNotFoundException: The given key '!' was not present in the dictionary. @    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at WingCalculatorShared.Operators.GetPrecedence(String symbol) in C:\Users\DSU\source\repos\WingCalculator\WingCalculatorShared\Operators.cs:line 98
   at WingCalculatorShared.Nodes.PreOperatorNode.get_Tier() in C:\Users\DSU\source\repos\WingCalculator\WingCalculatorShared\Nodes\PreOperatorNode.cs:line 14
   at WingCalculatorShared.Solver.<>c.<CreateTree>b__19_5(PreOperatorNode x) in C:\Users\DSU\source\repos\WingCalculator\WingCalculatorShared\Solver.cs:line 306
   at System.Linq.Enumerable.Min[TSource](IEnumerable`1 source, Func`2 selector)
   at WingCalculatorShared.Solver.CreateTree(Span`1 tokens) in C:\Users\DSU\source\repos\WingCalculator\WingCalculatorShared\Solver.cs:line 306
   at WingCalculatorShared.Solver.Solve(String s, Boolean setAns) in C:\Users\DSU\source\repos\WingCalculator\WingCalculatorShared\Solver.cs:line 65
   at WingCalculatorForms.MainForm.GetSolve(String s) in C:\Users\DSU\source\repos\WingCalculator\WingCalculatorForms\MainForm.cs:line 355
   ```
